apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "<%= name %>.fullname" . }}
  labels:
    app: {{ template "<%= name %>.name" . }}
    chart: {{ template "<%= name %>.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "<%= name %>.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.annotations }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "<%= name %>.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "<%= name %>.appenv" . | indent 12 }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.app.health.path }}
              port: {{ .Values.app.health.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
